defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "carlesgf@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  [acme.tlsChallenge]
  [[acme.domains]]
    main = "carlesandchristine.figuerola.info"
    sans = ["carlesichristine.figuerola.info", "christineandcarles.figuerola.info", "christineicarles.figuerola.info"]

[file]
[frontends]
  [frontends.website_frontend]
  backend = "website_backend"
    [frontends.website_frontend.routes.main_route]
    rule = "HostRegexp: {subdomain:[a-z]+}"

[backends]
  [backends.website_backend]
    [backends.website_backend.servers.localhost]
    url = "http://localhost:8000"
