branch-defaults:
  changes:
    environment: wedding-env
    group_suffix: null
  master:
    environment: wedding-env
environment-defaults:
  wedding-env:
    branch: null
    repository: null
global:
  application_name: wedding-site
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
